### ISSUE TITLE
When common base token WETH is selected it shows as MTX

### ISSUE THREAD

**Issue by crisog** [1Hive/honeyswap-interface#42]
![image](https://user-images.githubusercontent.com/40803711/120833696-18cb2280-c530-11eb-869d-34940225c270.png)

**Comment by onbjerg** [comment]
I think this is fixed by https://github.com/1Hive/honeyswap-sdk/pull/7 since the old address was actually for MTX

**Comment by crisog** [comment]
> I think this is fixed by [1Hive/honeyswap-sdk#7](https://github.com/1Hive/honeyswap-sdk/pull/7) since the old address was actually for MTX, can you confirm?

Yea, this was fixed with that PR. I've just confirmed it and it's now working correctly.
