### ISSUE TITLE
Super slow performance

### ISSUE THREAD

**Issue by onbjerg** [1Hive/honeyswap-interface#47]
The UI is extremely sluggish, sometimes dipping to less than 1 frame per second when clicking the text fields and/or the token and network selector. I'm not entirely sure why, but it seems that there is some updating logic that takes more than a second (sometimes 2-3 seconds) that is run whenever one of these points in the UI are clicked.

I've posted a perf dump from Firefox in the Tulip Discord, but this should be easily reproducible from any browser that has perf tools built-in

**Comment by ceresbzns** [comment]
Choosing wallet/network seems to resolve the issue. Can we confirm?

**Comment by crisog** [comment]
This was solved in #48.
