### ISSUE TITLE
Routing seems to be ignoring the GIV/TEC & GIV/NODE pools?

### ISSUE THREAD

**Issue by GriffGreen** [1Hive/honeyswap-interface#71]
<img width="571" alt="Screen Shot 2022-03-28 at 7 57 05 PM" src="https://user-images.githubusercontent.com/14945613/160511260-921fa587-e1d3-4986-a9e6-3557480f4ad5.png">

That's the wrong route...

All the liquidity is GIV/TEC

https://info.honeyswap.org/#/token/0x5df8339c5e282ee48c0c7ce8a7d01a73d38b3b27

And if you trade GIV for TEC it works well.. with much less slippage:
<img width="508" alt="Screen Shot 2022-03-28 at 7 59 13 PM" src="https://user-images.githubusercontent.com/14945613/160511423-66d14fd4-396d-4084-ab2f-c94601c7961c.png">

**Comment by laurenluz** [comment]
+1 on this! help!!

**Comment by GriffGreen** [comment]
GIV/NODE also needs to be added to routing... look at this difference in slippage!

<img width="574" alt="Screen Shot 2022-04-06 at 12 26 24 PM" src="https://user-images.githubusercontent.com/14945613/162033158-d60d8d4d-0abf-4cec-bcee-783b04f58994.png">

<img width="591" alt="Screen Shot 2022-04-06 at 12 26 30 PM" src="https://user-images.githubusercontent.com/14945613/162033134-3aa3a207-f68c-40d4-a2e3-defbf9bfe4cd.png">

**Comment by kamikazebr** [comment]
https://github.com/1Hive/honeyswap-interface/pull/72 - Fixed here @GriffGreen and @laurenluz

**Comment by laurenluz** [comment]
Oh YES
